[workspace]
members = [
    "crates/types",
    "crates/crypto",
    "crates/codec",
    "crates/ai_entities",
    "crates/copilot",
    "crates/governance",
    "crates/p2p",
    "crates/node",
    "crates/state",
    "crates/execution",
    "crates/smt",
    "crates/mempool",
    "crates/consensus_types",
    "crates/consensus",
    "crates/genesis",
    "tools/tx-generator",
    "tools/genesis-generator",
    "tools/novai-cli",
    "sdk/novai-sdk",
    "crates/ai_service",
]

resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

