"""Ed25519 keypair management.

Mirrors the file format used by ``novai-cli keygen``: a raw 32-byte ed25519
seed on disk with 0o600 permissions on Unix. A key generated by the CLI is
loadable by this module without any conversion, and vice versa.
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Union

from nacl.signing import SigningKey, VerifyKey

from novai_sdk.crypto import address_from_pubkey

PathLike = Union[str, "os.PathLike[str]"]


@dataclass(frozen=True)
class Keypair:
    """An ed25519 signing key plus its derived public key and 32-byte address.

    The seed is the canonical on-disk representation (32 bytes, matches
    ``novai-cli`` and ``ed25519_dalek::SigningKey::from_bytes``). The
    ``signing_key`` and ``verifying_key`` are pre-instantiated PyNaCl objects
    so callers do not need to know about the underlying library.
    """

    seed: bytes
    signing_key: SigningKey
    verifying_key: VerifyKey
    pubkey: bytes
    address: bytes

    @classmethod
    def generate(cls) -> Keypair:
        """Generate a fresh keypair using the OS CSPRNG."""
        sk = SigningKey.generate()
        return cls._from_signing_key(sk)

    @classmethod
    def from_seed(cls, seed: bytes) -> Keypair:
        """Construct a keypair from a 32-byte ed25519 seed."""
        if len(seed) != 32:
            raise ValueError(f"seed must be exactly 32 bytes, got {len(seed)}")
        return cls._from_signing_key(SigningKey(seed))

    @classmethod
    def load(cls, path: PathLike) -> Keypair:
        """Load a keypair from a raw 32-byte seed file (CLI-compatible format)."""
        p = Path(path)
        data = p.read_bytes()
        if len(data) != 32:
            raise ValueError(
                f"key file at {p} must be exactly 32 bytes (raw ed25519 seed), got {len(data)}"
            )
        return cls.from_seed(data)

    def save(self, path: PathLike, *, mode: int = 0o600) -> None:
        """Write the seed as a raw 32-byte file with restrictive permissions.

        On POSIX systems the file is created with ``mode`` (default 0o600 =
        read/write for owner only). On Windows the mode is ignored.
        """
        p = Path(path)
        p.write_bytes(self.seed)
        if sys.platform != "win32":
            os.chmod(p, mode)

    def sign(self, message: bytes) -> bytes:
        """Sign ``message`` and return the raw 64-byte ed25519 signature."""
        return bytes(self.signing_key.sign(message).signature)

    @property
    def pubkey_hex(self) -> str:
        """Hex-encoded public key (64 lowercase chars, no ``0x`` prefix)."""
        return self.pubkey.hex()

    @property
    def address_hex(self) -> str:
        """Hex-encoded NOVAI address (64 lowercase chars, no ``0x`` prefix)."""
        return self.address.hex()

    @classmethod
    def _from_signing_key(cls, sk: SigningKey) -> Keypair:
        vk = sk.verify_key
        pubkey_bytes = bytes(vk)
        address = address_from_pubkey(pubkey_bytes)
        return cls(
            seed=bytes(sk),
            signing_key=sk,
            verifying_key=vk,
            pubkey=pubkey_bytes,
            address=address,
        )

    def __repr__(self) -> str:
        return f"Keypair(address={self.address_hex})"
