#!/usr/bin/env node
//
// Freeze every console page to plain text, into the repository.
//
// WHY THIS EXISTS: gate C4 was only recoverable after a session died because a
// rendered snapshot of the C3 console survived in a rescue copy outside the
// repo. The falsifier could attack the exact artifact that had been reviewed,
// rather than a reconstruction of it. That should not depend on a rescue copy,
// so the snapshot lives here and is regenerated by a script, which means it can
// be diffed and re-derived instead of trusted.
//
// It is a text rendering, not a copy of the HTML, for the same reason the C3
// one was: an adversarial reader should read what a visitor reads. Markup is
// still on disk in the pages themselves if a finding needs it.
//
// Usage:
//   node scripts/freeze-console.mjs                    write the snapshots
//   node scripts/freeze-console.mjs --check            fail if they are stale
//   node scripts/freeze-console.mjs [--web-root <dir>] [--out <dir>]
//
// --web-root and --out exist so this gate can be exercised against a doctored
// copy of the page set rather than only against the working tree. Every other
// generator here already takes them; this one did not, which is precisely why
// it was the one gate with no test proving it can fail.
//

import { readFileSync, writeFileSync, existsSync, mkdirSync, renameSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));

function parseArgs(argv) {
  const args = { webRoot: resolve(SCRIPT_DIR, ".."), out: null, check: false };
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === "--web-root") args.webRoot = resolve(argv[++i]);
    else if (argv[i] === "--out") args.out = resolve(argv[++i]);
    else if (argv[i] === "--check") args.check = true;
    else fail(`unknown argument: ${argv[i]}`);
  }
  if (!args.out) args.out = join(args.webRoot, "snapshots");
  return args;
}

const ARGS = parseArgs(process.argv);
const WEB_ROOT = ARGS.webRoot;
const OUT = ARGS.out;

const PAGES = [
  "console.html",
  "console/rpc.html",
  "console/errors.html",
  "console/transactions.html",
  "console/entities.html",
  "console/sdks.html",
  "console/network.html",
  "console/verify.html",
  "console/all.html",
  "console/names.html",
];

function fail(msg) {
  console.error(`freeze-console: FAIL: ${msg}`);
  process.exit(1);
}

const ENTITIES = new Map([
  ["&amp;", "&"], ["&lt;", "<"], ["&gt;", ">"], ["&quot;", '"'], ["&#39;", "'"], ["&nbsp;", " "],
]);

/**
 * HTML to reading text.
 *
 * Code blocks are fenced with [CODE] so a reader of the snapshot can tell a
 * runnable example from prose, which is the distinction that matters most when
 * auditing this page. Table rows keep their pipes so a row stays one line and
 * cells stay separable; that is what made the index auditable last time.
 */
function toText(html) {
  let s = html;
  s = s.replace(/<!--[\s\S]*?-->/g, "");
  s = s.replace(/<(script|style)\b[\s\S]*?<\/\1>/gi, "");
  s = s.replace(/<pre\b[^>]*>([\s\S]*?)<\/pre>/gi, (_, body) => `\n[CODE]\n${body}\n[/CODE]\n`);
  s = s.replace(/<\/(h1|h2|h3|p|li|div|section|figcaption|tr|dd|dt)>/gi, "\n");
  s = s.replace(/<\/(td|th)>/gi, " | ");
  s = s.replace(/<br\s*\/?>/gi, "\n");
  s = s.replace(/<[^>]+>/g, "");
  // Named entities are decoded, because &quot; and &lt; inside a JSON fence are
  // noise between the reader and the shape.
  //
  // NUMERIC references are deliberately left alone. The page emits &#8212; for
  // the 503 body, because the node genuinely sends an em dash and a client
  // matching that string has to see the real byte, while console.html itself
  // must stay ASCII for the dash gate. Decoding it here would put a forbidden
  // character into a file the dash gate walks, and the honest fix is not to
  // exempt the file: an auditor reading `Service Unavailable &#8212; too many`
  // learns the useful thing, which is that the page deliberately emits U+2014
  // there rather than the hyphen it used to publish.
  for (const [k, v] of ENTITIES) s = s.split(k).join(v);
  s = s
    .split("\n")
    .map((l) => l.replace(/[ \t]+/g, " ").trimEnd())
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
  return s.trim() + "\n";
}

const snapshotFor = (rel) => join(OUT, rel.replace(/\//g, "__").replace(/\.html$/, ".txt"));

function main() {
  const check = ARGS.check;
  if (!check) mkdirSync(OUT, { recursive: true });
  let stale = 0;
  let lines = 0;
  for (const rel of PAGES) {
    const src = join(WEB_ROOT, rel);
    if (!existsSync(src)) fail(`${rel} does not exist, so it cannot be frozen`);
    const text = toText(readFileSync(src, "utf8"));
    lines += text.split("\n").length;
    const out = snapshotFor(rel);
    if (check) {
      if (!existsSync(out)) fail(`--check: ${out} does not exist; run npm run console:freeze and commit it`);
      if (readFileSync(out, "utf8") !== text) {
        stale += 1;
        console.error(`  stale: ${rel}`);
      }
      continue;
    }
    const tmp = out + ".tmp";
    writeFileSync(tmp, text);
    renameSync(tmp, out);
  }
  if (check && stale) fail(`${stale} snapshot(s) are stale; run npm run console:freeze and commit the result`);
  console.log(
    check
      ? `freeze-console: check ok (${PAGES.length} snapshots match the pages)`
      : `freeze-console: wrote ${PAGES.length} snapshot(s), ${lines} lines of reading text`
  );
}

main();
