import repoStats from "./repo-stats.generated.json";
import { floorTo } from "@/lib/format";

// Derived from repo-stats.generated.json (regenerated by npm run stats,
// freshness enforced by prebuild). Validators is a configuration fact of the
// fleet, not an operational liveness claim.
export const STATS: { value?: number; suffix?: string; label: string; prefix?: string; textOnly?: string }[] = [
  { textOnly: "Active", label: "Private Testnet Running" },
  { value: 4, suffix: "", label: "Validators", prefix: "" },
  { value: floorTo(repoStats.tests.value, 100), suffix: "+", label: "Tests", prefix: "" },
];
