[package]
name = "novai-consensus"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
novai-types = { path = "../types" }
novai-consensus-types = { path = "../consensus_types" }
novai-crypto = { path = "../crypto" }
novai-codec = { path = "../codec" }
novai-execution = { path = "../execution" }
novai-state = { path = "../state" }
mempool = { path = "../mempool" }
ed25519-dalek = "=2.1.1"

[dev-dependencies]
rand_core = { version = "0.6", features = ["getrandom"] }